version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app
  app:
    image: php:8.1-fpm
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./:/var/www/html
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: isucon
      MYSQL_USER: isucon
      MYSQL_PASSWORD: isucon
