services:
  web:
    image: nginx:1.23
    container_name: web
    volumes:
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    links:
      - app

  app:
    image: php:8.1-fpm
    container_name: app
    links:
      - mysql
    volumes:
      - ./php/public:/var/www/html

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment:
      - "TZ=Asia/Tokyo"
      - "MYSQL_ROOT_HOST=%"
      - "MYSQL_ROOT_PASSWORD=root"
    ports:
      - "3306:3306"

volumes:
  mysql:
